#!/bin/bash -e

# eos-external-apps-enable - Initialize the external apps repo setup
# Copyright (C) 2016 Endless Mobile, Inc.
#
# Authors:
#	Dan Nicholson <nicholson@endlessm.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

ext_apps_repo=/var/lib/flatpak-external-apps
ext_apps_remote=eos-external-apps

mkdir -p "$ext_apps_repo"

# add the remote to the system flatpak repository
flatpak remote-add --no-gpg-verify --if-not-exists ${ext_apps_remote} \
        "${ext_apps_repo}"

# ensure the settings are correct regardless
flatpak remote-modify ${ext_apps_remote} --no-gpg-verify \
        --url "file://${ext_apps_repo}"
