#!/bin/bash -e

# eos-external-apps-remove - Remove a runtime from the system
# Copyright (C) 2016 Endless Mobile, Inc.
#
# Authors:
#	Joaquim Rocha <jrocha@endlessm.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

function help {
    echo "$0"
    echo "Usage:"
    echo "  $0 APP_NAME BRANCH"
    echo ""
    echo "APP_NAME              the app name (e.g. org.myorg.MyApp)"
    echo "BRANCH                the branch of the app"
}

APPNAME=$1
BRANCH=$2

if [ -z "$APPNAME" ]; then
   echo "$0: Need the app name"
   help
   exit 1
fi

if [ -z "$BRANCH" ]; then
    BRANCH="master"
fi

# Remove the bundle
echo "Remove $APPNAME/$BRANCH..."

flatpak uninstall -v --runtime "$APPNAME" "$BRANCH"

echo "$APPNAME/$BRANCH was uninstalled"
